runtime: python
env: flex
service: discover-demo
runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "3.9"

entrypoint: streamlit run About.py --server.port $PORT

env_variables:
    SEARCH_ENGINE_ID: discover-search-demo_1692025142073