runtime: python
env: flex

runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "3.9"

entrypoint: streamlit run streamlit_app.py --server.port $PORT

# The App Engine Service Account Requires the Following Permissions
# -Logs Writer
# -Storage Object Viewer